### ISSUE TITLE
New custom rule is not being considered

### ISSUE THREAD

**Issue by augusto-altman** [markdalgleish/allthethings.js#2]
When I change the rules in a middle of an execution the previous rule remains cached and the new one is never considered.

Below there is a code snippet to reproduce the bug:

``` javascript
function foobarFunc(number) {
    return number % 2 === 0;
}

var numbers = [1, 2, 3, 4], temp;

console.log(foobarFunc.fromThe(numbers)); //Expected [false, true, false, true]

temp = allthethings.rules.filter;
allthethings.rules.filter = /foobar/;

console.log(foobarFunc.fromThe(numbers)); //Expected [2, 4]
```

I came out with a fix for this. I will send a pull request soon.

**Comment by markdalgleish** [comment]
This was kind of a joke project, and I haven't touched it in 2 years. Are you actually using this in production?

**Comment by augusto-altman** [comment]
No, I'm not using this. I ended up in the repo, read the code and found the bug. Giving the fact that you haven't touched the code since a lot and that the bug was very easy to fix, I opened the bug  and created a pull request with the fix jaja.
Sorry if I bother you with this.
